java com.tasc.Convert C:\alp\configs\aef-config\aftransportation.bat
java com.tasc.Convert C:\alp\configs\aef-config\Alp.bat
java com.tasc.Convert C:\alp\configs\aef-config\chalkview.bat
java com.tasc.Convert C:\alp\configs\aef-config\DBSetup.bat
java com.tasc.Convert C:\alp\configs\aef-config\ForcePackage.bat
java com.tasc.Convert C:\alp\configs\aef-config\fuelassessor.bat
java com.tasc.Convert C:\alp\configs\aef-config\LRC.bat
java com.tasc.Convert C:\alp\configs\aef-config\Marines.bat
java com.tasc.Convert C:\alp\configs\aef-config\NameServ.bat
java com.tasc.Convert C:\alp\configs\aef-config\node.bat
java com.tasc.Convert C:\alp\configs\aef-config\node3.bat
java com.tasc.Convert C:\alp\configs\aef-config\nodeAEF.bat
java com.tasc.Convert C:\alp\configs\aef-config\nodep.bat
java com.tasc.Convert C:\alp\configs\aef-config\nodepAEF.bat
java com.tasc.Convert C:\alp\configs\aef-config\NodeTest.bat
java com.tasc.Convert C:\alp\configs\aef-config\NodeTest2.bat
java com.tasc.Convert C:\alp\configs\aef-config\setlibpathAEF.bat
java com.tasc.Convert C:\alp\configs\aef-config\Society.bat
java com.tasc.Convert C:\alp\configs\aef-config\squadron.bat
java com.tasc.Convert C:\alp\configs\aef-config\SubsNode.bat
